jobs:
  bucket: r2://lmrun
  controller:
    resources:  # same spec as 'resources' in a task YAML
      cloud: aws
      region: us-east-1
      # default: 4+
      cpus: 2+  # number of vCPUs, max concurrent spot jobs = 2 * cpus
      # default: 100
      disk_size: 25

allowed_clouds:
  - aws
  - cloudflare
  - paperspace

aws:
  labels:
    config: lmrun
  vpc_name: lmrun
  security_group_name:
    - "*": lmrun
  # IAM instance profile selection by cluster name
  remote_identity:
    - "main*": main
    - "*": lmrun

