name: Linter Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install linters
        run: |
          pip install poetry
          poetry install --with dev
      - name: Check black
        run: poetry run black --check .
      - name: Check flake8
        run: poetry run flake8 .
      - name: Check pylint
        # explicitly pass subfolders to pylint 2: '.' doesn't recurse
        run: poetry run pylint */
