name: Linter Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: pip install uv
      - name: Check ruff formatter
        # install --extra dev dependencies on first uv run
        run: uv run --extra dev ruff format --check
      - name: Check ruff linter
        run: uv run ruff check
      - name: Check pylint
        # explicitly pass subfolders to pylint 2: '.' doesn't recurse
        run: uv run pylint */
